### ISSUE TITLE
《Flutter 入门指南》1.0.0 版本重写提纲

### ISSUE THREAD

**Issue by icepy** [icepy/flutter-book#1]
- 第一篇 万物起源
  - 第一章 移动端混合开发历史
    - 1.1 PhoneGap
    - 1.2 React Native & Weex
    - 1.4 小程序
    - 1.3 大前端的意义
  - 第二章 Flutter 介绍
    - 2.1 什么是 Flutter
    - 2.2 Flutter 的优势和缺陷
    - 2.3 2019 官方 roadmap 是什么
    - 2.4 Flutter 未来的发展趋势
    - 2.5 和其他跨平台方案的对比
  - 第三章 国际惯例 Hello World
    - 3.1 搭建 Flutter 运行环境
    - 3.2 演示 Hello World
- 第二篇 从零开始
  - 第一章 基础 Widget
    - 1.1 StatelessWidget
    - 1.2 StatefulWidget
  - 第二章 路由管理
    - 2.1 静态路由
    - 2.2 可传参数的动态路由
  - 第三章 其他管理
    - 3.1 包管理详解
      - 1.1.0 详解 pubspec.yaml
      - 1.1.1 如何开发一个 Dart Package
    - 3.2 资源管理详解
  - 第四章 调试技巧
    - 4.1 通过错误堆栈来定位问题
    - 4.2 使用断点调试功能
    - 4.3 开启辅助线来调试 UI
    - 4.4 使用Web调试工具
    - 4.5 Dart 线程模型以及异常捕获
    - 4.6 阅读源码解决问题
    - 4.7 善用issues
- 第三篇 渐进增强
  - 第一章 关于布局的思考和封装 Widget 的意义
  - 第二章 事件和通知
    - 2.1 Pointer 事件
    - 2.2 GestureDetector 手势
    - 2.3 Notification 通知
  - 第三章 生命周期
    - 3.1 Widget 生命周期详解
    - 3.2 App 生命周期
  - 第四章 异步处理
    - 4.1 callback
    - 4.2 Future
    - 4.3 async 和 await
    - 4.4 Stream
  - 第五章 文件操作和网络请求
    - 5.1 使用 Dart IO 来读写文件
    - 5.2 HttpClient
    - 5.3 Socket API
  - 第六章 JSON 序列化和本地存储
    - 对 JSON 序列化的一些理解
    - shared_preferences 的使用
  - 第七章 Native
    - 7.1 如何将 Flutter 集成到已有的 iOS 工程中
    - 7.2 谈谈 Flutter 通信和插件
    - 7.3 将应用发布到 iOS 平台
- 第四篇 流畅动画
  - 第一章 Flutter 动画和动画结构
  - 第二章 自定义路由过渡动画
- 第五篇 质量保证
  - 第一章 Testing
  - 第二章 性能分析
  - 第三章 性能最佳实践
- 第六篇 优雅设计
  - 第一章 使用 Stream 更新简单的 UI
  - 第二章 使用 Redux 来共享状态和管理单一数据
  - 第三章 使用 Bloc 来处理数据并更新 UI
  - 第四章 使用 Hooks 来处理数据并更新 UI
  - 第五章 选择的权衡
- 附录
  - 第一章 常用 Flutter 命令
    - 1.1 flutter doctor
    - 1.2 flutter upgrade
    - 1.3 flutter build
    - 1.4 flutter create
    - 1.5 flutter run
  - 第二章 为 JavaScript 开发人员准备的 Dart 参考教程
    - 1.1 常量和变量
    - 1.2 内置类型
      - 2.1 Number
      - 2.2 String
      - 2.3 Booleans
      - 2.4 Lists
      - 2.5 Sets
      - 2.6 Maps
      - 2.7 Runes
      - 2.8 Symbols
    - 1.2 函数
    - 1.3 枚举
    - 1.4 字符串模板
    - 1.5 模块的导入和导出
    - 1.6 类
    - 1.7 异步
    - 1.8 泛型
  - 第三章 常用 Widget 详解
    - 1.1 Row
    - 1.2 Column
    - 1.3 Scaffold
    - 1.4 Container
    - 1.5 Padding, Align, Center
    - 1.6 Stack, IndexedStack
    - 1.7 ListView
    - 1.8 GridView
    - 1.9 Transform
    - 1.10 Dialog

**Comment by wangbaojin2008** [comment]
加油 兄弟

**Comment by icepy** [comment]
> 加油 兄弟

0.0 万一我拿去卖钱呢？哈哈。

**Comment by icepy** [comment]
已废弃；
